- src/main/java/EventManager.java
What else is needed for EventManager?
> Finished EventManager...?

- src/main/java/Event.java
> Updated Event with documentations

- src/main/java/EmployeeManager.java
- src/test/java/EmployeeManagerTest.java
- src/test/java/stored_employees.txt
Added method getID to EmployeeManager which accepts an ArrayList of Employees and returns an array of integers (which are those Employees IDs)
Added tests for the constructor and addEmployee()
> EmployeeManager getID and some tests

- src/test/java/EventTest.java
> Finished EventTest.java

- src/main/java/CateringSystem.java
- src/main/java/CreateEventCommand.java
- src/main/java/ICommand.java
- src/main/java/Main.java
Command interface's execute() has generic return type. CateringSystem now uses Command object to create new events instead of directly calling the Managers' methods. Moved EmployeeManager and EventManager construction out of CateringSystem and into Main (now we inject Managers into System). Moved lines that prompt the user to input event info in Main and made them a method.
> Changes to Main, CateringSystem. Implemented Command interface and CreateEventCommand

- src/main/java/Dish.java
- src/main/java/Ingredient.java
Add more structure classes of Meal class extension
> Add more structure classes of Meal class extension

- src/main/java/managers/EventManager.java
- src/main/java/meals/Meal.java
- src/test/java/EventManagerTest.java
- src/test/java/EventTest.java
- src/test/java/MealTest.java
I'm still trying to deal with the getEventByID, many methods in other classes would have to throw the EventNotFound exception if I have getEventByID to throw it, so maybe we need to find a design pattern...?
> Basically Maggie's pull request without confilcts

- phase1/Phase 1 Progress Report.md
feel free to change/add what you worked on in phase 1 in the summary section
> added more to progress report

- src/main/java/managers/EventManager.java
so that it throws and handles the exception
> Update getEventByID method

- phase1/Design Document.md
Lmk if anything should be changed!
> Finished design document!

- src/test/java/EmployeeTest.java
Need to figure out why the TestEquals is not passing
> Added some test cases in EmployeeTest

- src/main/java/events/Event.java
- src/main/java/meals/Meal.java
- src/main/java/meals/MealSetter.java
- src/test/java/EmployeeTest.java
- src/test/java/EventManagerTest.java
- src/test/java/EventTest.java
- src/test/java/MealTest.java
Mainly changing the mealtype objects to specific subclass types in test files. 
Also modifying the switch statement in MealSetters. 
Override equals method in Meal class.
> Fixed some problems with the test files

- src/main/java/managers/EmployeeManager.java
Fixed file pathing in EmployeeManager
To do:
Make sure everything involving Meal works.
Write EmployeeManager tests and make sure they pass.
Make sure UserManager tests pass.
> Fixed file pathing in EmployeeManager

- src/main/java/commands/ModifyEventCommand.java
- src/main/java/front_end/CateringSystem.java
- src/main/java/managers/EventManager.java
Updated EventManager.java with enhanced date setter and numAttendees setter which check the number of available employees 
Updated a few lines in other files in order for these setters to work properly
> Updated EventManager.java and added CreateMealCommand.java

- src/main/java/commands/ViewEventCommand.java
- src/main/java/front_end/Main.java
- src/main/java/managers/EventManager.java
This update clear EventNotFoundError from completely destroying the whole program from running
> Updated Main.java and ViewEventCommand.java

- src/test/java/CateringSystemTest.java
The testModifyEventAttendees did not pass, I commented out but right now the coverage is 84% so I think we are good for now. Other tests are all passing
> Added CateringSystemTest

- src/main/java/managers/EventManager.java
Fixed EventManager HashMap initialization.
> viewEvent fix

- src/test/java/CateringSystemTest.java
- src/test/java/EventManagerTest.java
Added users package in data_files 
Import usermanager in EventManager, and create a user to allow test to pass
> Update CateringSystem test and EventManager test files

- phase1/Design Document.md
> Improved design document

- src/main/java/events/Event.java
- src/main/java/managers/EventManager.java
- src/main/java/meals/Breakfast.java
- src/main/java/meals/Dinner.java
- src/main/java/meals/Lunch.java
- src/main/java/meals/Meal.java
- src/test/java/MealTest.java
Modified meal class and subclasses, event class, to include different employees. modified meal tests to include types as well.
> Integrated employee subclasses in code

- phase2/Design Document.md
> Updated Design Document

- src/main/java/commands/ICommand.java
- src/main/java/exceptions/EventNotFoundError.java
- src/main/java/exceptions/EventNotFoundException.java
- src/main/java/exceptions/InvalidPasswordException.java
- src/main/java/exceptions/UserNotFoundException.java
- src/main/java/front_end/CateringSystem.java
- src/main/java/front_end/Main.java
- src/main/java/managers/EventManager.java
- src/main/java/managers/UserManager.java
- src/test/java/CateringSystemTest.java
- src/test/java/EventManagerTest.java
UPDATE:
Wrote specific Exceptions:
InvalidPasswordException
UserNotFoundException
Updated commands and classes to keep in line with changes
Renamed/refactored EventNotFoundError to EventNotFoundException
> Additional Exceptions

- phase2/Design Document.md
- src/test/java/EventTest.java
Also updated EventTest to reflect changes in Employee and Meal class
> Update design document with design principle 4

- phase2/Design Document.md
UPDATE:
Design Document Principle 3
Progress Report update for Zi Xuan
> Design Document updates

- src/main/java/managers/EventManager.java
- fixed eventmanager so that when logging in to an account with existing events, the newly created event would replace the old ones
> fixed eventmanager

- phase2/Design Document.md
wait why is my part still missing lol
> updated progress report

- src/main/java/employees/Employee.java
- src/main/java/read_writers/EmployeeManagerReadWriter.java
- src/test/java/EmployeeManagerTest.java
- src/test/java/EmployeeTest.java
Bug in original test file is due to equals method for GregorianCalendar that compared dates to the millisecond, changed methods in Employee file that used the equals method to pass the test.
> Updated EmployeeManager test and related files

- phase2/Design Document.md
- src/test/java/UserManagerTest.java
fixed error in testGetUserNull() method to allow all test in file to pass.
also updated design document
> UserManagerTest method typo fix

- src/main/java/meals/Breakfast.java
- src/main/java/meals/Dinner.java
- src/main/java/meals/Dish.java
- src/main/java/meals/Ingredient.java
- src/main/java/meals/Lunch.java
- src/main/java/meals/Meal.java
- src/main/java/users/RatingSystem.java
1 (a) Devolve certain tasks and parameters originally in the Abstract Meal class (superclass) to the subclasses.
1 (b) Reduced the use of Hashtable/Hashmaps.
1 (c) Simplify createEmployee() method.
2. Remove the unnecessary RatingSystem class.
3. Create some setters for future program expansions.
> 1. Major Update on Meal packages to better implement Composite Design Pattern and Factory Design Pattern
